# Generated by Django 5.0.6 on 2024-05-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='JobStaus',
            field=models.BooleanField(default=True),
        ),
    ]
