# Generated by Django 5.0.6 on 2024-05-13 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_job_created_at_alter_job_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=256, primary_key=True, serialize=False)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('experience', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=100)),
                ('jobID', models.IntegerField(unique=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('coverletter', models.TextField(validators=[django.core.validators.MinLengthValidator(500)])),
            ],
        ),
    ]
