# Generated by Django 5.0.6 on 2024-05-13 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='experience',
            new_name='YearOfExperience',
        ),
        migrations.AlterField(
            model_name='application',
            name='coverletter',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
