# Generated by Django 5.0.6 on 2024-05-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_application_jobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
