# Generated by Django 5.0.6 on 2024-05-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
