# Generated by Django 5.0.6 on 2024-05-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rename_job_application_jobid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='position',
        ),
    ]
