# Generated by Django 5.0.6 on 2024-05-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_job_jobstaus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='JobStaus',
            new_name='JobStatus',
        ),
    ]
