# Generated by Django 5.0.6 on 2024-05-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_experience_application_yearofexperience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jobID',
            field=models.IntegerField(),
        ),
    ]
