# Generated by Django 5.0.6 on 2024-05-23 00:52

import django.core.validators
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_application_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('YearsOfExperience', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='YearOfExperience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='coverletter',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
