# Generated by Django 5.0.6 on 2024-05-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_jobsearchmodel_alter_application_yearofexperience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='YearOfExperience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='coverletter',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
