# Generated by Django 5.0.6 on 2024-06-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isAdmin',
            new_name='is_company_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.AddField(
            model_name='user',
            name='companyName',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
