# Generated by Django 5.0.6 on 2024-06-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rename_isadmin_user_is_company_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_company_admin',
            new_name='Admin',
        ),
    ]
