# Generated by Django 5.0.6 on 2024-06-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_rename_is_company_admin_user_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Admin',
            new_name='is_company_admin',
        ),
    ]
