# Generated by Django 5.0.6 on 2024-06-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_rename_admin_user_is_company_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='companyName',
            new_name='company_name',
        ),
    ]
